name: "Integration test"
# NOTE: We're just running the tests that require earthdata login here; we
#       don't distinguish yet between unit and integration tests yet.

on:
  push:
    branches:
      - "main"
      - "development"


jobs:
  test:
    name: "Test"
    if: "github.repository == 'icesat2py/icepyx'"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Get user permissions"
        id: "checkAccess"
        uses: "actions-cool/check-user-permission@v2"
        with:
          require: "write"
          username: "${{ github.triggering_actor }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"


      - name: "Notify of permissions issue"
        uses: "actions/github-script@v7"
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for reporting! Integration tests have been skipped
                     due to lack of permissions.\n\n**Maintainers: avoid [pwn requests](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/)!**
                     Please review this PR for suspicious changes (especially
                     to GitHub Actions workflows), then, if everything looks good, re-run the job at
                     URL:
                     ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`,

            })

      - name: "Check User Permission"
        if: "steps.checkAccess.outputs.require-result == 'false'"
        run: |
          echo "${{ github.triggering_actor }} does not have permissions on this repo."
          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
          echo "Job originally triggered by ${{ github.actor }}."
          echo "Please re-run this job as a user with at least 'write' permissions on this repo."
          exit 1

      - uses: "./.github/actions/install-icepyx"
        with:
          python-version: "3.12"
          # IMPORTANT: This is _dangerous_ without the access check above!!
          ref: "${{  github.event.pull_request.head.sha }}"

      - name: "Run tests"
        env:
          EARTHDATA_USERNAME: "${{ secrets.EARTHDATA_USERNAME }}"
          EARTHDATA_PASSWORD: "${{ secrets.EARTHDATA_PASSWORD }}"
        run: |
          pytest icepyx/ --verbose --cov app \
            icepyx/tests/test_behind_NSIDC_API_login.py \
            icepyx/tests/test_auth.py

      - name: "Upload coverage report"
        uses: "codecov/codecov-action@v4.5.0"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
