name: "Unit test"
# NOTE: We're just skipping the tests requiring earthdata login here; we don't
#       distinguish yet between unit and integration tests.

on:
  pull_request:
  push:
    branches:
      - "main"
      - "development"


jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
      - uses: "./.github/actions/install-icepyx"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Run tests"
        run: |
          pytest icepyx/ --verbose --cov app \
            --ignore=icepyx/tests/test_behind_NSIDC_API_login.py \
            --ignore=icepyx/tests/test_auth.py

      - name: "Upload coverage report"
        uses: "codecov/codecov-action@v4.5.0"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
